version: 2

models:
  - name: stg_athletes
    description: ""
    columns:
      - name: athlete_key
        data_type: varchar
        description: ""
        tests:
          - unique
          - not_null

      - name: person_fullname
        data_type: varchar
        description: ""

      - name: audience
        data_type: varchar
        description: ""

      - name: wrestling_type
        data_type: varchar
        description: ""

      - name: weight_class_in_kg
        data_type: integer
        description: ""

      - name: rank
        data_type: integer
        description: ""

      - name: uww_points
        data_type: integer
        description: ""

      - name: is_current
        data_type: boolean
        description: ""

      - name: previous_rank
        data_type: integer
        description: ""

      - name: previous_season_rank
        data_type: integer
        description: ""

      - name: season
        data_type: integer
        description: ""

      - name: daterange_start
        data_type: date
        description: ""

      - name: daterange_end
        data_type: date
        description: ""

      - name: lastname
        data_type: varchar
        description: ""

      - name: firstname
        data_type: varchar
        description: ""

      - name: nationality
        data_type: varchar
        description: ""

      - name: person_gender
        data_type: varchar
        description: ""

      - name: person_birthdate
        data_type: date
        description: ""

      - name: person_profilepicture
        data_type: varchar
        description: ""

  - name: stg_events
    description: ""
    columns:
      - name: tournament_key
        data_type: varchar
        description: ""
        tests:
          - unique
          - not_null
      - name: title
        data_type: varchar
        description: ""

      - name: created_at_timestamp
        data_type: timestamp
        description: ""

      - name: changed_at_timestamp
        data_type: timestamp
        description: ""

      - name: event_start_date
        data_type: date
        description: ""

      - name: event_year
        data_type: bigint
        description: ""

      - name: event_end_date
        data_type: date
        description: ""

      - name: is_streaming_available
        data_type: boolean
        description: ""

      - name: twitter_hashtag
        data_type: varchar
        description: ""

      - name: branding
        data_type: varchar
        description: ""

      - name: field_branding_identifier
        data_type: varchar
        description: ""

      - name: field_event_type
        data_type: varchar
        description: ""

      - name: field_event_type_identifier
        data_type: varchar
        description: ""

      - name: country
        data_type: varchar
        description: ""

      - name: city
        data_type: varchar
        description: ""

      - name: program_url
        data_type: varchar
        description: ""

      - name: age_group
        data_type: varchar
        description: ""

      - name: wrestling_types
        data_type: varchar
        description: ""

      - name: country_code
        data_type: varchar
        description: ""

      - name: results_url
        data_type: varchar
        description: ""

      - name: session_start_date
        data_type: timestamp
        description: ""

      - name: session_end_date
        data_type: timestamp
        description: ""

      - name: status
        data_type: boolean
        description: ""

  - name: stg_matches
    description: ""
    columns:
      - name: match_key
        data_type: varchar
        description: ""

      - name: wrestler_a_key
        data_type: varchar
        description: ""

      - name: wrestler_b_key
        data_type: varchar
        description: ""

      - name: tournament_key
        data_type: varchar
        description: ""

      - name: wrestler_a
        data_type: varchar
        description: ""

      - name: wrestler_b
        data_type: varchar
        description: ""

      - name: score_a
        data_type: integer
        description: ""

      - name: score_b
        data_type: integer
        description: ""

      - name: match_result
        data_type: varchar
        description: ""

      - name: tournament_name
        data_type: varchar
        description: ""

      - name: weight_class_in_kg
        data_type: varchar
        description: ""

      - name: tournament_country
        data_type: varchar
        description: ""

      - name: tournament_month_year
        data_type: varchar
        description: ""

      - name: tournament_year
        data_type: varchar
        description: ""

